In [ ]:
"""待研究模块"""
ConfigSpace # 用于算法的参数空间配置

In [ ]:
"""Python官方文档
https://docs.python.org/zh-cn/3/reference/index.html
"""

In [ ]:
1. 概述
1.1. 其他实现
1.2. 标注
2. 词法分析
2.1. 行结构
2.2. 其他形符
2.3. 标识符和关键字
2.4. 字面值
2.5. 运算符
2.6. 分隔符
3. 数据模型
3.1. 对象、值与类型
3.2. 标准类型层级结构
3.3. 特殊方法名称
3.4. 协程
4. 执行模型
4.1. 程序的结构
4.2. 命名与绑定
4.3. 异常
5. 导入系统
5.1. importlib
5.2. 包
5.3. 搜索
5.4. 加载
5.5. 基于路径的查找器
5.6. 替换标准导入系统
5.7. 包相对导入
5.8. 有关 __main__ 的特殊事项
5.9. 开放问题项
5.10. 参考文献
6. 表达式
6.1. 算术转换
6.2. 原子
6.3. 原型
6.4. await 表达式
6.5. 幂运算符
6.6. 一元算术和位运算
6.7. 二元算术运算符
6.8. 移位运算
6.9. 二元位运算
6.10. 比较运算
6.11. 布尔运算
6.12. 赋值表达式
6.13. 条件表达式
6.14. lambda 表达式
6.15. 表达式列表
6.16. 求值顺序
6.17. 运算符优先级
7. 简单语句
7.1. 表达式语句
7.2. 赋值语句
7.3. assert 语句
7.4. pass 语句
7.5. del 语句
7.6. return 语句
7.7. yield 语句
7.8. raise 语句
7.9. break 语句
7.10. continue 语句
7.11. import 语句
7.12. global 语句
7.13. nonlocal 语句
8. 复合语句
8.1. if 语句
8.2. while 语句
8.3. for 语句
8.4. try 语句
8.5. with 语句
8.6. 函数定义
8.7. 类定义
8.8. 协程
9. 最高层级组件
9.1. 完整的 Python 程序
9.2. 文件输入
9.3. 交互式输入
9.4. 表达式输入
10. 完整的语法规范

In [2]:
python --help  # 可以看到 -m -v等参数的说明
help(np.allclose)  # 可看到模块和函数的帮助信息。函数显示的是定义下面的文本说明。
python -m 模块名  # 意思是将库中的python模块用作脚本去运行。
参考https://www.cnblogs.com/xueweihan/p/5118222.html

SyntaxError: invalid syntax (<ipython-input-2-89ab081e9e69>, line 3)

In [13]:
def ab():
    """
    sdfasdfsafaf
    """
    pass
help(ab)

Help on function ab in module __main__:

ab()
    sdfasdfsafaf



In [ ]:
python的setup功能如何实现

In [2]:
"""三元表达式"""
3 if 1==2 else 2

2

In [3]:
"""lambda函数"""

'lambda函数'

In [17]:
"""这种迭代空列表字段不会执行下面的语句，就没有循环，判断为空后直接退出循环。
"""
for i in []:
    print(3)
for i,j in dict().items():
    print(1)

In [23]:
"""三种格式化字符串的方法"""
print('Age: %s. Gender: %s' % (25, True))  # 这种方法不能传入list,dict等复杂数据格式
print('Hello, {0}, 成绩提升了 {1:.1f},列表{2}，字典{3}'.format('小明', 17.125,[1,2],{'a':666}))
r = [1,'a',[2,22]]
s = 3.12345
print(f'The area of a circle with radius {r} is {s:.2f}')

Age: 25. Gender: True
Hello, 小明, 成绩提升了 17.1,列表[1, 2]，字典{'a': 666}
The area of a circle with radius [1, 'a', [2, 22]] is 3.12


In [27]:
"""@带表点积"""
import numpy as np
arr1 = np.ones((2,5))*2
arr2 = np.ones((5,2))*3
print(arr1*arr1)
print(arr1@arr2)

[[4. 4. 4. 4. 4.]
 [4. 4. 4. 4. 4.]]
[[30. 30.]
 [30. 30.]]


# 异常，错误

In [15]:
"""try...except
如果使用else这个子句，那么必须放在所有的 except 子句之后。else 子句将在 try 子句没有发生任何异常的时候执行。
finally 语句无论是否发生异常都将执行最后的代码。
"""
try:  # 多个except子句情况下，只有一个excep会被执行。
    df = pd.read_csv(path, encoding='utf8', header=0, sep=',')
except BaseException as e:
    print(e, '文件类型错误，pandas无法打开{}\n'.format(path))
except OSError as err:  # 上面的excep包含下面的except，所以这个永远取不到。
    print(err)
except (RuntimeError,TypeError,NameError) as k:  # except可以处理多个异常，放在括号里成为元组。
    print(k)
except:    # 最后的except子句可忽略异常名称，它将被当作通配符。打印一个错误信息，然后再次把异常抛出。
    print("Unexpected error:", sys.exc_info()[0])
else:  # 必须放在所有的 except 子句之后。else 子句将在 try 子句没有发生任何异常的时候执行。
    if 'label' in df.columns:
        return df.drop(['label'], axis=1).values, df['label'].values
    else:
        raise Exception('读入的数据没有label列')
finally:
    pass

SyntaxError: 'return' outside function (<ipython-input-15-d64055a7154b>, line 17)

In [14]:
"""raise抛出异常
raise唯一的一个参数指定了要被抛出的异常。它必须是一个异常的实例或者是异常的类（也就是 Exception 的子类）。
如果你只想知道这是否抛出了一个异常，并不想去处理它，那么一个简单的 raise 语句就可以再次把它抛出。
"""
try:
    raise NameError('HiThere')
except NameError:
    print('An exception flew by!')
    raise



An exception flew by!


NameError: HiThere

In [16]:
"""断言可指定后面的内容"""
assert 1==2, 'asdfdf'

AssertionError: asdfdf