In [2]:
"""@带表点积，与*的区别"""
import numpy as np
arr1 = np.ones((2,5))*2
arr2 = np.ones((5,2))*3
print(arr1*arr1)
print(arr1@arr2)

[[4. 4. 4. 4. 4.]
 [4. 4. 4. 4. 4.]]
[[30. 30.]
 [30. 30.]]


[1, 3, 5, 7, 9]

In [86]:
"""map函数的使用,搭配lambda"""
list(map(lambda x: x**2, [1, 2, 3, 4, 5]))

[1, 4, 9, 16, 25]

In [15]:
"""iter用法,配合next"""
x = iter([1,2,3,5,8])
next(x)
any(x)
"""zip的用法"""
list(zip(range(5), range(10,15), range(20,25)))
"""slice用于固定切片,slice(start, stop[, step])"""
s = slice(0,5,2)
[11,12,13,14,15][s]
"""filter函数，效率还可以"""
list(filter(lambda x: x%2==1, [1, 2, 3,]))
list(filter(lambda x:isinstance(x, str), [1, 'a',None,'']))
list(filter(bool, [1,0,True,False]))

[1, True]

In [82]:
"""locals在函数中的应用"""
def f1():
    a=1
    def subf():
        print('im children')
    d=dict(a='a')
    print(locals())
f1()

{'a': 1, 'subf': <function f1.<locals>.subf at 0x000001E9D86B51E0>, 'd': {'a': 'a'}}


In [95]:
"""print的end参数"""
for i in range(3): print(i, end='x\n')  # end默认'\n'

0x
1x
2x


In [107]:
"""enumerate用法"""
[(i,j) for i,j in enumerate(list('asdf'),100)]

[(100, 'a'), (101, 's'), (102, 'd'), (103, 'f')]

In [80]:
"""vars() 函数返回对象object的属性和属性值的字典对象。
不带参数时，vars() 的行为类似 locals()。"""
class Runoob:
    a = 1
print(vars(Runoob))
{'a': 1, '__module__': '__main__', '__doc__': None}

{'__module__': '__main__', 'a': 1, '__dict__': <attribute '__dict__' of 'Runoob' objects>, '__weakref__': <attribute '__weakref__' of 'Runoob' objects>, '__doc__': None}


{'__doc__': None, '__module__': '__main__', 'a': 1}

In [141]:
"""计算函数"""
abs(-3)  # 3
all([True,True,False])  # False
any([True,True,False])  # True
bool(3)  # True
complex(3,8)  # (3+8j)
divmod(5,3)  # (1, 2)
5//3  # 1
5%3  # 2
5/3  # 1.6666
frozenset(['a','b','c'])  # frozenset({'a', 'b', 'c'})
len('abc')  # 3
min([1,5,2])  # 1
max([1,5,2])  # 5
pow(2,3)  # 8
sum([1,2],100)  # 103
list(range(2,6,2))  # [2, 4] range(start, stop[, step])
round(1.123, 2)  # 1.12 round(number[, ndigits])
reversed(['a','b','c'])  # 对一个序列取反，并且返回的是迭代器，可被next()调用

In [84]:
"""管理函数"""
dir()  # dir(函数或变量等对像)可以返回这个对像的所有方法和属性
globals()  # 返回所有全局变量
type(object)  # type
id(x)  # 返回变量的内存地址
input()  # 输入内容转化为字符串

 sdfa


'sdfa'

In [41]:
"""格式转换"""
ascii(123)  # '123'
bin(-3)  # '-0b11'
bytearray([1,2,3])  # bytearray(b'\x01\x02\x03')
bytes([1,2,3])  # b'\x01\x02\x03'
int('12')  # 12
float('1e-03')  # 0.001
hex(15)  # '0xf' 十六进制
oct(16)  # '0o20' 八进制
ord('中')  # 20013
hash('abc')  # 返回哈希值

-5683383048676464012

#  待处理

In [ ]:
"""lambda函数"""
"""3.7新功能"""
breakpoint()

In [100]:
class Coordinate:
    x = 10
    y = -5
    z = 0
delattr(Coordinate, 'z') 

In [ ]:
class A(object):
    attr1 = 'a'
a = A()
getattr(a, 'attr1')
getattr(a, 'non_existent', 3)

In [146]:
hasattr('object','attr')

False

In [ ]:
setattr(object, name, value)

In [ ]:
isinstance(object, classinfo)

In [ ]:
issubclass(class, classinfo)

In [113]:
v = memoryview(bytearray("abdg", 'utf-8'))

In [119]:
v[0]

97

In [130]:
v[1:3]

In [131]:
v[1:3].tobytes()

b'bd'

In [ ]:
sorted(iterable, *, key=None, reverse=False)