# sklearn

In [1]:
#mod.__dict__用法
from sklearn.linear_model import LinearRegression
import numpy as np
x = [[1],[2],[3]];y = [1,2,3]
line_mod = LinearRegression()
line_mod.fit(x,y)
print(line_mod.score(x,y))  #R2 coefficient of detemination
line_mod.__dict__.keys()

1.0


dict_keys(['fit_intercept', 'normalize', 'copy_X', 'n_jobs', 'coef_', '_residues', 'rank_', 'singular_', 'intercept_'])

In [103]:
#打印所有模型评估方法
import sklearn
sklearn.metrics.SCORERS.keys()

dict_keys(['explained_variance', 'r2', 'max_error', 'neg_median_absolute_error', 'neg_mean_absolute_error', 'neg_mean_squared_error', 'neg_mean_squared_log_error', 'neg_root_mean_squared_error', 'neg_mean_poisson_deviance', 'neg_mean_gamma_deviance', 'accuracy', 'roc_auc', 'roc_auc_ovr', 'roc_auc_ovo', 'roc_auc_ovr_weighted', 'roc_auc_ovo_weighted', 'balanced_accuracy', 'average_precision', 'neg_log_loss', 'neg_brier_score', 'adjusted_rand_score', 'homogeneity_score', 'completeness_score', 'v_measure_score', 'mutual_info_score', 'adjusted_mutual_info_score', 'normalized_mutual_info_score', 'fowlkes_mallows_score', 'precision', 'precision_macro', 'precision_micro', 'precision_samples', 'precision_weighted', 'recall', 'recall_macro', 'recall_micro', 'recall_samples', 'recall_weighted', 'f1', 'f1_macro', 'f1_micro', 'f1_samples', 'f1_weighted', 'jaccard', 'jaccard_macro', 'jaccard_micro', 'jaccard_samples', 'jaccard_weighted'])

In [104]:
#toydata导出csv
import os
import numpy as np
import pandas as pd
from sklearn.datasets import load_boston
data_name = 'load_boston'
save_path = '.\\toy_datas'
def toy2csv(data_name, save_path):
    raw_toy = eval(data_name)()
    toy_df = pd.DataFrame(np.hstack([raw_toy.data, raw_toy.target.reshape(raw_toy.target.shape[0],1)]),
    columns=np.concatenate([raw_toy.feature_names,np.array(['label'])]))
    toy_df.to_csv(os.path.join(save_path,data_name.split('.')[-1] + '.csv'),index=False)
toy2csv(data_name, save_path)

In [105]:
#造数据
from sklearn.datasets import make_regression,make_classification
x,y = make_regression(n_samples=100,n_features=2,n_targets=1,noise=10)
x,y = make_classification(n_samples=300, n_features=2, n_redundant=0, n_informative=2, n_clusters_per_class=1, scale=100)

In [106]:
#preprocessing.scale
import numpy as np
from sklearn import preprocessing
x = (np.random.randn(12)*100).reshape(4,3)
x_norm = preprocessing.scale(x)
x_norm

array([[-0.4484455 , -0.97430073,  0.09942149],
       [ 1.58500167,  0.46262063,  1.08283385],
       [-1.13431093, -0.90730482, -1.6203804 ],
       [-0.00224524,  1.41898492,  0.43812506]])

In [107]:
# knn
from sklearn.datasets import load_iris
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
iris = load_iris();iris_x = iris.data;iris_y = iris.target
x_train,x_test,y_train,y_test = train_test_split(iris_x,iris_y,test_size=0.3)
knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(x_train,y_train)
knn.predict(x_test)
knn.score(x_test, y_test)

0.9555555555555556

In [108]:
#model_selection.cross_val_score
from sklearn.model_selection import cross_val_score
from sklearn.neighbors import KNeighborsClassifier
from sklearn.datasets import load_iris
iris = load_iris(); iris_x=iris.data; iris_y = iris.target
k_range = range(1,31)
k_scores = []
for k in k_range:
    knn = KNeighborsClassifier(n_neighbors=k)
    scores = cross_val_score(knn, iris_x, iris_y, cv=10, scoring='accuracy')
    k_scores.append(scores.mean())
print(k_scores)

[0.96, 0.9533333333333334, 0.9666666666666666, 0.9666666666666666, 0.9666666666666668, 0.9666666666666668, 0.9666666666666668, 0.9666666666666668, 0.9733333333333334, 0.9666666666666668, 0.9666666666666668, 0.9733333333333334, 0.9800000000000001, 0.9733333333333334, 0.9733333333333334, 0.9733333333333334, 0.9733333333333334, 0.9800000000000001, 0.9733333333333334, 0.9800000000000001, 0.9666666666666666, 0.9666666666666666, 0.9733333333333334, 0.96, 0.9666666666666666, 0.96, 0.9666666666666666, 0.9533333333333334, 0.9533333333333334, 0.9533333333333334]


In [109]:
#model_selection.learning_curve
from sklearn.model_selection import learning_curve
from sklearn.datasets import load_digits
from sklearn.svm import SVC
import numpy as np
digits = load_digits(); x = digits.data; y = digits.target
train_sizes, train_loss, test_loss = learning_curve(SVC(gamma=0.001), x, y, cv=10, scoring='neg_mean_absolute_error', train_sizes=[0.1, 0.25, 0.5, 0.75, 1])
train_loss_mean = -np.mean(train_loss, axis=1)
test_loss_mean = -np.mean(test_loss, axis=1)
print(train_loss_mean)
print(test_loss_mean)

[0.02236025 0.00891089 0.00519802 0.00313531 0.00519481]
[0.77852576 0.31707325 0.15642768 0.11298262 0.07626319]


In [110]:
#model_selection.validation_curve
from sklearn.model_selection import validation_curve
from sklearn.datasets import load_digits
from sklearn.svm import SVC
import numpy as np
digits = load_digits(); x = digits.data; y = digits.target
param_range = np.logspace(-6, -2.3, 5)
train_loss, test_loss = validation_curve(SVC(), x, y,param_name='gamma',param_range=param_range,cv=10, scoring='neg_mean_absolute_error')
train_loss_mean = -np.mean(train_loss, axis=1)
test_loss_mean = -np.mean(test_loss, axis=1)
print(train_loss_mean)
print(test_loss_mean)

[ 2.62557526  0.3591164   0.09002674  0.00890408 -0.        ]
[2.65036934 0.47471757 0.21270329 0.08906269 0.33278709]


In [111]:
#svm
from sklearn import datasets
from sklearn import preprocessing
from sklearn import model_selection as modsel
from sklearn import svm
x,y = datasets.make_classification(n_samples=300, n_features=2, n_redundant=0, n_informative=2, n_clusters_per_class=1, scale=100)
x = preprocessing.scale(x)
x_train, x_test, y_train, y_test = modsel.train_test_split(x, y, test_size=0.3)
clf = svm.SVC()
clf.fit(x_train, y_train)
print(clf.score(x_test,y_test))
import pickle
with open('.\\mod_restore\\pickle_clf.pickle', 'wb') as f:
    pickle.dump(clf, f)
with open('.\\mod_restore\\pickle_clf.pickle', 'rb') as f:
    clf2 = pickle.load(f)
print(clf2.predict(x[0:5]))
from sklearn.externals import joblib
joblib.dump(clf, '.\\mod_restore\\joblib_clf.pkl')
clf3 = joblib.load('.\\mod_restore\\joblib_clf.pkl')
print(clf3.predict(x[0:7]))

1.0
[0 0 0 1 0]
[0 0 0 1 0 0 0]
